image: ruby:2.3

pages:
  stage: deploy
  script:
  - "gem install jekyll -v 3.8"
  - gem install bundler
  - gem update --system
  - bundle install
  - bundle exec jekyll build -d public/
  artifacts:
    paths:
    - public
  only:
  - master
